theme: jekyll-theme-cayman
title: Rohit Das's Website
description: This is a collection of my thoughts on a veriety of topics.  This is an experiment at this point.  Constructive feedback always welcome.
